// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/icons/icon-black-128.png"
    | "/icons/icon-black-16.png"
    | "/icons/icon-black-32.png"
    | "/icons/icon-black-48.png"
    | "/icons/icon-gray-128.png"
    | "/icons/icon-gray-16.png"
    | "/icons/icon-gray-32.png"
    | "/icons/icon-gray-48.png"
    | "/icons/icon-green-128.png"
    | "/icons/icon-green-16.png"
    | "/icons/icon-green-32.png"
    | "/icons/icon-green-48.png";
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>;
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
